<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38907" started-at="2019-10-24T15:57:06 IST" finished-at="2019-10-24T15:57:45 IST">
    <groups>
    </groups>
    <test name="FirstTest" duration-ms="38907" started-at="2019-10-24T15:57:06 IST" finished-at="2019-10-24T15:57:45 IST">
      <class name="POC.lumaLogin.LoginTest">
        <test-method status="PASS" signature="browserSetup(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:POC.lumaLogin.LoginTest@42d8062c]" name="browserSetup" is-config="true" duration-ms="22958" started-at="2019-10-24T15:57:06 IST" finished-at="2019-10-24T15:57:29 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[60]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[MAC]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[http://ec2-18-223-118-61.us-east-2.compute.amazonaws.com/magento4/magento2/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetup -->
        <test-method status="PASS" signature="login()[pri:101, instance:POC.lumaLogin.LoginTest@42d8062c]" name="login" duration-ms="14325" started-at="2019-10-24T15:57:29 IST" finished-at="2019-10-24T15:57:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="verifyTitle()[pri:102, instance:POC.lumaLogin.LoginTest@42d8062c]" name="verifyTitle" duration-ms="405" started-at="2019-10-24T15:57:44 IST" finished-at="2019-10-24T15:57:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Subscribe Button] but found [Subscribe]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Subscribe Button] but found [Subscribe]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at POC.lumaLogin.LoginMethods.titleValidate(LoginMethods.java:45)
at POC.lumaLogin.LoginTest.verifyTitle(LoginTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method status="PASS" signature="quit()[pri:103, instance:POC.lumaLogin.LoginTest@42d8062c]" name="quit" duration-ms="1187" started-at="2019-10-24T15:57:44 IST" finished-at="2019-10-24T15:57:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- POC.lumaLogin.LoginTest -->
    </test> <!-- FirstTest -->
  </suite> <!-- Suite -->
</testng-results>
